name: CI

on:
  pull_request:
    branches: [dev, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install langchain-pinecone (skip its bad deps pin)
        run: python -m pip install --no-deps langchain-pinecone==0.2.6

      - name: Set test environment variables
        run: |
          echo "DISCORD_TOKEN=test_discord_token_12345" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=test_openai_key_12345" >> $GITHUB_ENV
          echo "PINECONE_API_KEY=test_pinecone_key_12345" >> $GITHUB_ENV
          echo "PINECONE_CALENDAR_INDEX=test-calendar-index" >> $GITHUB_ENV
          echo "SUPABASE_URL=https://test.supabase.co" >> $GITHUB_ENV
          echo "SUPABASE_API_KEY=test_supabase_key_12345" >> $GITHUB_ENV
          echo "TENANTS_FILE=tests/fixtures/tenants_sample.json" >> $GITHUB_ENV

      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings --ignore=tests/integration
