# .github/workflows/ci.yml

name: CI

# Run on pushes to main, dev, or any feature branch, and on PRs against dev
on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Setup Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Run your tests
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
