name: CI

on:
  pull_request:
    branches: [dev, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install langchain-pinecone without its deps
        run: python -m pip install --no-deps langchain-pinecone==0.2.6

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings

